name: Build & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up -d

    - name: Run tests
      run: Invoke-Pester -Path .\Tests -Output Detailed