name: Publish Releases to Hub

# When its time to do a release do a full cross platform build for all supported
# architectures and push all of them to Docker Hub.
# Only trigger on semver shaped tags.
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: windows-2019
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push
        shell: pwsh
        working-directory: .
        env:
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}        
        run: |
          docker login -u kewalaka -p $env:TOKEN
          docker build . --file Dockerfile --tag kewalaka/chocolatey-server:0.2.5
          docker image push kewalaka/chocolatey-server:0.2.5
          docker logout

